DATA_PATH = "data"
DEFAULT_FONT_PATH = f"{DATA_PATH}/JetBrainsMonoNL-Regular.ttf"
BOLD_FONT_PATH = f"{DATA_PATH}/JetBrainsMonoNL-Bold.ttf"
MAIN_WND = "Main Window"
PROGRESS_FILE = f"{DATA_PATH}/progress.json"
SCORE_TEXT = "score_text"
PROGRESS_BAR = "progress_bar"
